### ISSUE TITLE
How to upload res folder into Flash

### ISSUE THREAD

**Issue by asypost** [sipeed/MaixUI#1]
How to upload res folder into Flash,It seems that folder is not supported by spiflashfs

**Comment by junhuanchen** [comment]
Py exported to maixpy_spiffs_image.py exported to maixpy_spiffs_img and fired it into firmware Flash. Until then, we still use SD card to complete the function development.

![image](https://user-images.githubusercontent.com/32978053/89749677-4a838080-dafb-11ea-9091-acceb93fe05a.png)

python gen_spiffs_image.py ../../projects/maixpy_k210/config_defaults.mk

**Comment by asypost** [comment]
image.Image("/flash/res/icons/app_camera.bmp")
