### ISSUE TITLE
运行maixui时出现下图所示的错误

### ISSUE THREAD

**Issue by whlyg** [sipeed/MaixUI#4]
![O@O5S9`D0}46~4P)MY7XTV8](https://user-images.githubusercontent.com/104193946/164645248-89093ca4-4ec7-4b8b-8c24-33aac0cebd4c.png)

**Comment by junhuanchen** [comment]
在该目录下找不到文件,请检查该文件是否存在

请先学习一下 python import 的绝对路径和相对路径用法

**Comment by whlyg** [comment]
文件是存在的，运行的脚本是app文件夹下的app_cube.py，然后提示出错的包在lib文件夹下






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sipeed/MaixUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sipeed/MaixUI] 运行maixui时出现下图所示的错误 (Issue #4)





 
在该目录下找不到文件,请检查该文件是否存在
 
请先学习一下 python import 的绝对路径和相对路径用法

**Comment by junhuanchen** [comment]
您好,文件并不存在 
![image](https://user-images.githubusercontent.com/32978053/164679338-5fbd5975-69b4-4a5e-a214-bdf456747e19.png)
您应该直接将 lib 放入 sd 卡根目录

**Comment by junhuanchen** [comment]
您可以先学习一下 os.getcwd 和  os.chdir 是如何使用的.

**Comment by whlyg** [comment]
我用的是maixcube开发板，把lib等文件夹放在根目录下之后，是需要将app下的app_cube.py也放在根目录下并取代main.py吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月22日(周五) 下午5:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sipeed/MaixUI] 运行maixui时出现下图所示的错误 (Issue #4)




 
您可以先学习一下 os.getcwd 和  os.chdir 是如何使用的.

**Comment by whlyg** [comment]
将lib等文件夹放在根目录，将app文件夹下的app_cube改名为main也放在根目录，出现这个错误，并且每过一段时间系统自动重置一次





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sipeed/MaixUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sipeed/MaixUI] 运行maixui时出现下图所示的错误 (Issue #4)





 
您好,文件并不存在
 
 您应该直接将 lib 放入 sd 卡根目录
